"""Execute read-only queries against supported databases.

Security policy:
- SQL: Only SELECT statements are allowed; a keyword blocklist rejects
  DDL and DML (DROP, DELETE, INSERT, UPDATE, ALTER, TRUNCATE, EXEC …).
- MongoDB: $out and $merge stages are blocked in aggregation pipelines.
- Maximum 200 rows/documents returned to protect memory.
"""

from __future__ import annotations

import datetime
import json
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

_SQL_FORBIDDEN_RE = re.compile(
    r"\b(drop|delete|truncate|insert|update|alter|create|exec|execute|grant|revoke|call|merge)\b",
    re.IGNORECASE,
)
_MONGO_FORBIDDEN_STAGES = {"$out", "$merge"}
_MAX_ROWS = 200


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def execute_query(db_type: str, url: str, query: str) -> list[dict[str, Any]]:
    """Run *query* against the specified database and return rows as dicts.

    Args:
        db_type: mysql / postgresql / mssql / mongodb / other
        url:     Connection string
        query:   SQL string or JSON MongoDB query object

    Returns:
        List of row-dicts (max 200 entries).
    """
    t = db_type.lower()
    if t in {"mysql", "postgresql", "mssql", "other"}:
        return _sql_execute(url, query)
    if t == "mongodb":
        return _mongo_execute(url, query)
    raise ValueError(f"ประเภทฐานข้อมูล '{db_type}' ไม่รองรับการ query")


# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------
def _sql_execute(url: str, sql: str) -> list[dict[str, Any]]:
    from sqlalchemy import create_engine, text  # type: ignore[import-untyped]
    from app.db_inspector import _normalize_sql_url

    if _SQL_FORBIDDEN_RE.search(sql):
        bad = _SQL_FORBIDDEN_RE.search(sql).group()  # type: ignore[union-attr]
        raise ValueError(
            f"คำสั่ง SQL ไม่ได้รับอนุญาต (พบ '{bad}') — ใช้ได้เฉพาะ SELECT เท่านั้น"
        )

    engine = create_engine(_normalize_sql_url(url), pool_pre_ping=True)
    try:
        with engine.connect() as conn:
            result = conn.execute(text(sql))
            keys = list(result.keys())
            rows = [
                dict(zip(keys, row))
                for row in result.fetchmany(_MAX_ROWS)
            ]
        return rows
    finally:
        engine.dispose()


# ---------------------------------------------------------------------------
# MongoDB
# ---------------------------------------------------------------------------
def _mongo_execute(url: str, query_str: str) -> list[dict[str, Any]]:
    """Execute a MongoDB query expressed as a JSON string.

    Accepted formats (generated by LLM):

    Simple find::

        {"collection": "orders", "filter": {"status": "active"},
         "sort": {"date": -1}, "projection": {"name": 1}}

    Aggregation pipeline::

        {"collection": "orders", "pipeline": [{"$match": {...}}, ...]}
    """
    from pymongo import MongoClient  # type: ignore[import-untyped]
    from app.db_inspector import _extract_mongo_dbname

    try:
        query_obj: dict[str, Any] = json.loads(query_str)
    except json.JSONDecodeError as exc:
        raise ValueError(f"รูปแบบ MongoDB query ไม่ถูกต้อง (JSON parse error): {exc}") from exc

    coll_name = query_obj.get("collection")
    if not coll_name:
        raise ValueError("MongoDB query ต้องมี field 'collection'")

    # Security: block dangerous aggregation stages
    if "pipeline" in query_obj:
        for stage in query_obj["pipeline"]:
            for key in stage:
                if key in _MONGO_FORBIDDEN_STAGES:
                    raise ValueError(f"MongoDB stage '{key}' ไม่ได้รับอนุญาต")

    db_name = _extract_mongo_dbname(url)
    client: MongoClient = MongoClient(url, serverSelectionTimeoutMS=5000)
    try:
        coll = client[db_name][coll_name]

        if "pipeline" in query_obj:
            cursor = coll.aggregate(query_obj["pipeline"])
        else:
            filt = query_obj.get("filter", {})
            proj = query_obj.get("projection") or None
            cursor = coll.find(filt, proj)
            if "sort" in query_obj:
                cursor = cursor.sort(list(query_obj["sort"].items()))

        rows: list[dict[str, Any]] = []
        for doc in cursor:
            rows.append(_serialize_doc(doc))
            if len(rows) >= _MAX_ROWS:
                break
        return rows
    finally:
        client.close()


def _serialize_doc(doc: dict[str, Any]) -> dict[str, Any]:
    """Convert BSON-specific types to JSON-serializable Python types."""
    result: dict[str, Any] = {}
    for k, v in doc.items():
        if k == "_id":
            continue
        if hasattr(v, "binary"):          # ObjectId / Binary
            result[k] = str(v)
        elif isinstance(v, (datetime.datetime, datetime.date)):
            result[k] = v.isoformat()
        elif isinstance(v, dict):
            result[k] = _serialize_doc(v)
        elif isinstance(v, list):
            result[k] = [_serialize_doc(i) if isinstance(i, dict) else i for i in v]
        else:
            result[k] = v
    return result
